# Generated by Django 5.1.5 on 2025-01-22 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_is_correct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
