# Generated by Django 5.1.5 on 2025-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_disliked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
